### ISSUE TITLE
Swerv EH1 Core Compliance Test

### ISSUE THREAD

**Issue by YeuzhiHere** [riscv-software-src/riscof#23]
I want to do compliance test for Swerv EH1 Core using riscof. But I got following error after installing riscof and running "riscof --help"
![Riscof](https://user-images.githubusercontent.com/58413763/134661089-8b6e24ad-9a4f-42da-b4b5-fa49547622a8.PNG)

Please guide and resolve this issue.

regards

**Comment by pawks** [comment]
Could you please post the details of the environment you are using and also the output of the `pip list` command.

**Comment by YeuzhiHere** [comment]
Yeah, I am using Ubuntu 20.04. And output for pip list is;
![riscof1](https://user-images.githubusercontent.com/58413763/134849918-3caf0838-1179-40ba-896a-562d18da935d.PNG)
![riscof2](https://user-images.githubusercontent.com/58413763/134849922-e3c03c50-cc14-42fd-8e27-2efc4fcfc460.PNG)
![riscof3](https://user-images.githubusercontent.com/58413763/134849924-95d38a6f-c846-4c94-93a1-b4c22f96328f.PNG)
![riscof4](https://user-images.githubusercontent.com/58413763/134849925-a22335bd-2e1f-4d75-834e-8922ffdd0698.PNG)

**Comment by pawks** [comment]
Upgrading the version of `click` to the latest should fix your error. Try the following command:
`pip install -U click`

**Comment by YeuzhiHere** [comment]
Ok
