### ISSUE TITLE
Change the reference model to one that supports misaligned lw/sw 

### ISSUE THREAD

**Issue by aignacio** [riscv-software-src/riscof#41]
Hey guys,

thanks for nice work with RISCOF framework!, I'd like ask you if there's a way to use spike isa-sim or another RV simulator as a reference model that supports misaligned lw/sw.  I discovered recently that there's a way to enable misaligned support on Sail RISC-V C-simulator but the problem is that it seems to not be fully working as per ticket down below. If there's an alternative for it'd be really great.

https://github.com/riscv/sail-riscv/issues/156

I've attached my report to show that only `misaligned-sw` are currently failing with this model....
[report.html.zip](https://github.com/riscv-software-src/riscof/files/8305341/report.html.zip)

**Comment by neelgala** [comment]
in the config.ini you can use [spike_parallel](https://gitlab.com/incoresemi/riscof-plugins/-/tree/master/spike_parallel) as the reference plugin and it should generate the reference signatures. Let me know if that fails.

**Comment by pawks** [comment]
You will also have to modify [this](https://gitlab.com/incoresemi/riscof-plugins/-/blob/master/spike_parallel/riscof_spike_parallel.py#L129) line to add the necessary argument which enables hw misaligned accesses.

**Comment by aignacio** [comment]
Thanks @neelgala and @pawks, 

@pawks you mean adding [`--enable-misaligned`](https://github.com/riscv-software-src/riscv-isa-sim/blob/c6ec6f3582eb2ae106dff95e569b7da927910629/riscv/riscv.ac#L57) to the line you mentioned?

**Comment by pawks** [comment]
> Thanks @neelgala and @pawks, 
> 
> @pawks you mean adding [`--enable-misaligned`](https://github.com/riscv-software-src/riscv-isa-sim/blob/c6ec6f3582eb2ae106dff95e569b7da927910629/riscv/riscv.ac#L57) to the line you mentioned? 

Yes.

**Comment by neelgala** [comment]
I think you will need to re-build spike while configuring with `--enable-misaligned`. I don't see a cli arg to enable misaligned.

**Comment by aignacio** [comment]
What are the required parameters for using `spike_parallel`?
![image](https://user-images.githubusercontent.com/5991372/159040671-9a7bb289-b53f-4a17-8c94-ec61a4d203a0.png)

**Comment by neelgala** [comment]
you may need to specify ispec and psec which could just be copied from lines 11 and 12 - they will not be ignored by spike when cofigured as reference model.

**Comment by pawks** [comment]
The `00` you see at the start of the line is infact the last byte of the store from the previous word. Let us consider the instruction `80000138`, it is a `sw` instruction with the address `80002216`. So it should modify bytes `80002216 through 8000221b`, which is infact the 2 bytes to the left on line 3. This particular store can also be looked at as a sequence of instructions which generate the same result. 
```
  sh a1,2047(a0)
  addi a0,a0,2
  srli a1,a1,16
  sh a1,2047(a0)
```
It looks like your implementation is not updating the bytes of the next word in case of a misaligned `sw` instruction. This would have been a legal output incase the store of the bytes in the next word violated any security permissions but the implementation has to attempt to store 4 bytes.

**Comment by aignacio** [comment]
Hey @pawks,

thanks for the answer, I was indeed concluding the same yesterday. It took me some time to realize that because it sounds a bit strange this behaviour, even more when you consider standard protocols such as the ones in the AMBA family where the size of the transfer needs to be aligned with the address. Anyway, it is what it is, thanks again for the help.
