### ISSUE TITLE
Typo in installation instructions

### ISSUE THREAD

**Issue by davidharrishmc** [riscv-software-src/riscof#47]
In the installation instructions, rename "arch-tests" to "arch-test".

$ riscof --verbose info arch-tests --clone

**Comment by pawks** [comment]
This has been fixed on [this](https://github.com/riscv-software-src/riscof/blob/doc-dependency-fix/docs/source/arch-tests.rst#cloning-the-riscv-arch-test-repo) branch and will soon be merged into master.
