### ISSUE TITLE
Documentation: inconsistent use of "isa and platform yamls" vs. "ISA and Platform yamls"

### ISSUE THREAD

**Issue by jeras** [riscv-software-src/riscof#52]
I am going through the entire documentation preparing spelling, grammar, consistency fixes.
This are all small/trivial/cosmetic changes.

What would be the preferred capitalization of the phrase in the issue title? I encountered both versions.

**Comment by pawks** [comment]
Using consistent capitalization would certainly be preferable.

**Comment by jeras** [comment]
OK, I will use the capitalized version "ISA and Platform yamls" in my documentation pull request.
