### ISSUE TITLE
hanging at "INFO | Runing Tests on Reference Model"

### ISSUE THREAD

**Issue by hyperion009** [riscv-software-src/riscof#82]
when running test cases, flow  was hanging at "INFO | Runing Tests on Reference Model"

what's going on? what else can I　ｄｏ？
![Uploading 微信图片_20230302202658.png…]()

**Comment by pawks** [comment]
There are two possible reasons for this. Either the tests were running in the background but didn't finish running yet(possible if D is included in the ISA) or one of the tests is encountering a trap when it is not supposed to. Could you possibly monitor the processes on your system to see if there is a single process spawned by riscof which takes more than 5 mins to finish.

**Comment by hyperion009** [comment]
thank Pawks，Let me check it
